import { useState } from 'react';
import { Copy, Check, Loader2, Download, ChevronDown, Sparkles } from 'lucide-react';
import type { EnhanceResponse } from '../hooks/useEnhance';
import jsPDF from 'jspdf';
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from 'docx';
import { saveAs } from 'file-saver';

interface OutputDisplayProps {
    data: Partial<EnhanceResponse>;
    activeTone: 'professional' | 'conversational' | 'story' | 'bold';
    isPending?: boolean;
}

const toneMapping: Record<string, keyof EnhanceResponse> = {
    professional: 'Professional',
    conversational: 'Conversational',
    story: 'Storytelling',
    bold: 'Bold/Contrarian'
};

export default function OutputDisplay({ data, activeTone, isPending }: OutputDisplayProps) {
    const [copied, setCopied] = useState(false);
    const [showDownloadMenu, setShowDownloadMenu] = useState(false);

    const mappedKey = toneMapping[activeTone];
    const activeData = data[mappedKey] || (data as any)[activeTone];
    const hasData = !!activeData;

    const copyToClipboard = () => {
        if (!activeData) return;
        const fullText = `${activeData.enhancedPost || ''}\n\n${(activeData.hashtags || []).join(' ')}`;
        navigator.clipboard.writeText(fullText);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const sanitizeFilename = (title: string, extension: string) => {
        const cleanTitle = title.replace(/[^a-z0-9]/gi, '_').replace(/_{2,}/g, '_').toLowerCase();
        const finalTitle = cleanTitle.length > 0 ? cleanTitle : 'ghostpost_export';
        const timestamp = new Date().toISOString().split('T')[0];
        return `${finalTitle}_${timestamp}.${extension}`;
    };

    const downloadWord = async () => {
        if (!activeData) return;
        try {
            const title = activeData.title || 'Enhanced Content';
            const children = [
                new Paragraph({
                    text: title.toUpperCase(),
                    heading: HeadingLevel.HEADING_1,
                    alignment: AlignmentType.CENTER,
                    spacing: { after: 400 },
                }),
                new Paragraph({
                    children: [
                        new TextRun({ text: `Tone: ${mappedKey}`, bold: true }),
                        new TextRun({ text: ` | Generated by GhostPost`, color: "666666" }),
                        new TextRun({ text: ` | ${new Date().toLocaleDateString()}`, color: "999999" }),
                    ],
                    alignment: AlignmentType.CENTER,
                    spacing: { after: 600 },
                }),
            ];
            
            const postContent = activeData.enhancedPost || '';
            postContent.split('\n').forEach((line: string) => {
                const trimmed = line.trim();
                if (trimmed) {
                    children.push(new Paragraph({ 
                        text: trimmed, 
                        spacing: { after: 200 },
                        alignment: AlignmentType.LEFT
                    }));
                } else {
                    children.push(new Paragraph({ spacing: { after: 100 } }));
                }
            });

            const doc = new Document({ 
                title,
                creator: "GhostPost",
                sections: [{ children }] 
            });
            const blob = await Packer.toBlob(doc);
            saveAs(blob, sanitizeFilename(title, 'docx'));
            setShowDownloadMenu(false);
        } catch (error) {
            console.error('Word export error:', error);
        }
    };

    const downloadPDF = async () => {
        if (!activeData) return;
        try {
            const doc = new jsPDF();
            const title = activeData.title || 'Enhanced Content';
            const content = activeData.enhancedPost || '';
            
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(22);
            doc.text(title.toUpperCase(), 105, 30, { align: 'center' });
            
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(10);
            doc.setTextColor(150);
            doc.text(`Tone: ${mappedKey} | Generated by GhostPost`, 105, 40, { align: 'center' });
            
            doc.setTextColor(0);
            doc.setFontSize(11);
            const splitText = doc.splitTextToSize(content, 170);
            
            let cursorY = 55;
            const pageHeight = doc.internal.pageSize.height;
            const marginBottom = 20;

            splitText.forEach((line: string) => {
                if (cursorY + 10 > pageHeight - marginBottom) {
                    doc.addPage();
                    cursorY = 20;
                }
                doc.text(line, 20, cursorY);
                cursorY += 7;
            });

            const pageCount = (doc as any).internal.getNumberOfPages();
            for (let i = 1; i <= pageCount; i++) {
                doc.setPage(i);
                doc.setFontSize(8);
                doc.setTextColor(180);
                doc.text(`Page ${i} of ${pageCount}`, 105, pageHeight - 10, { align: 'center' });
            }

            doc.save(sanitizeFilename(title, 'pdf'));
            setShowDownloadMenu(false);
        } catch (error) {
            console.error('PDF export error:', error);
        }
    };

    const downloadPlainText = () => {
        if (!activeData) return;
        const blob = new Blob([activeData.enhancedPost], { type: 'text/plain' });
        saveAs(blob, sanitizeFilename(activeData.title || 'Enhanced Content', 'txt'));
        setShowDownloadMenu(false);
    };

    return (
        <div className="flex flex-col h-full space-y-1 text-[13px] font-normal">
            {/* Row 1: Header (Scores & Download) */}
            <div className="flex items-center justify-between py-[2px] border-t border-white/5 whitespace-nowrap">
                <div className="flex items-center gap-6">
                    <div className="flex items-center gap-2">
                        <span className="text-gray-500">Hook:</span>
                        <span className="text-primary font-medium">{activeData?.hookScore || 0}/10</span>
                    </div>
                    <div className="flex items-center gap-2">
                        <span className="text-gray-500">Confidence:</span>
                        <span className="text-green-400 font-medium">{activeData?.confidenceScore || 0}%</span>
                    </div>
                </div>

                {hasData && (
                    <div className="relative">
                        <button
                            onClick={() => setShowDownloadMenu(!showDownloadMenu)}
                            className="flex items-center gap-2 text-gray-400 hover:text-primary transition-all"
                        >
                            <Download size={14} />
                            <ChevronDown size={12} className={`transition-transform ${showDownloadMenu ? 'rotate-180' : ''}`} />
                        </button>

                        {showDownloadMenu && (
                            <div className="absolute right-0 mt-1 w-28 bg-[#1a1a1a] border border-white/10 rounded-[2px] shadow-xl z-50 flex flex-col">
                                <button onClick={downloadPDF} className="w-full text-left px-3 py-[1px] hover:bg-white/5 text-gray-300 text-[11px] font-medium">
                                    PDF
                                </button>
                                <button onClick={downloadWord} className="w-full text-left px-3 py-[1px] hover:bg-white/5 text-gray-300 text-[11px] font-medium">
                                    Word
                                </button>
                                <button onClick={downloadPlainText} className="w-full text-left px-3 py-[1px] hover:bg-white/5 text-gray-300 text-[11px] font-medium">
                                    Text
                                </button>
                            </div>
                        )}
                    </div>
                )}
            </div>

            {/* Row 2: Variant Selection Info */}
            <div className="flex items-center justify-between py-[2px] border-b border-white/5 whitespace-nowrap min-h-[24px]">
                {activeData ? (
                    <>
                        <div className="flex items-center gap-2">
                            <Sparkles size={12} className="text-primary" />
                            <span className="text-gray-500 text-[11px] tracking-wider">{mappedKey} Variant</span>
                        </div>
                        <button
                            onClick={copyToClipboard}
                            className="hover:text-primary transition-colors flex items-center gap-1 text-gray-500 text-[11px]"
                        >
                            {copied ? <Check size={12} /> : <Copy size={12} />}
                            {copied ? 'Copied' : 'Copy'}
                        </button>
                    </>
                ) : (
                    <div className="text-gray-600 italic text-[11px]">No variant selected</div>
                )}
            </div>

            {/* Content Area */}
            <div className="flex-1 flex flex-col pt-2 min-h-[500px]">
                {isPending ? (
                    <div className="flex-1 flex flex-col items-center justify-center text-gray-500 gap-4">
                        <Loader2 size={24} className="animate-spin text-primary" />
                        <p className="animate-pulse">Agents are crafting your content...</p>
                    </div>
                ) : activeData ? (
                    <div className="space-y-4">
                        <div className="text-gray-300 whitespace-pre-wrap leading-relaxed border border-white/5 p-4 rounded-[2px] bg-white/[0.02]">
                            {activeData.enhancedPost}
                        </div>

                        {activeData.hashtags && activeData.hashtags.length > 0 && (
                            <div className="flex flex-wrap gap-2 pt-2">
                                {activeData.hashtags.map((tag: string) => (
                                    <span key={tag} className="text-primary/70 text-[11px]">#{tag.replace('#', '')}</span>
                                ))}
                            </div>
                        )}

                        {activeData.hookTip && (
                            <div className="p-3 border-l-2 border-primary/20 bg-primary/5 text-gray-400 italic text-[12px]">
                                "{activeData.hookTip}"
                            </div>
                        )}
                    </div>
                ) : (
                    <div className="flex-1 flex flex-col items-center justify-center text-gray-600 italic">
                        <Sparkles size={32} className="opacity-10 mb-4" />
                        <p>Adjust your settings on the left and click Generate.</p>
                    </div>
                )}
            </div>
        </div>
    );
}
