import { useState } from 'react';
import { Copy, Check, Info, Loader2, Briefcase, MessageSquare, BookOpen, Zap, Download, Wand2, Sparkles } from 'lucide-react';
import type { EnhanceResponse } from '../hooks/useEnhance';
import jsPDF from 'jspdf';
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from 'docx';
import { saveAs } from 'file-saver';
import { useGenerateHook } from '../hooks/useEnhance';

interface OutputDisplayProps {
    data: Partial<EnhanceResponse>;
    onGenerate: (tone: string) => void;
    isPending?: boolean;
}

type ToneType = keyof EnhanceResponse;

export default function OutputDisplay({ data, onGenerate, isPending }: OutputDisplayProps) {
    const [copied, setCopied] = useState(false);
    const [activeTab, setActiveTab] = useState<ToneType>('Professional');
    const [generatedHooks, setGeneratedHooks] = useState<Record<string, string>>({});
    const generateHookMutation = useGenerateHook();

    const tones: { id: ToneType; icon: any; label: string }[] = [
        { id: 'Professional', icon: Briefcase, label: 'Professional' },
        { id: 'Conversational', icon: MessageSquare, label: 'Conversational' },
        { id: 'Storytelling', icon: BookOpen, label: 'Story' },
        { id: 'Bold/Contrarian', icon: Zap, label: 'Bold' },
    ];

    const activeData = data[activeTab];
    const hasData = !!activeData;

    const copyToClipboard = () => {
        if (!activeData) return;
        const fullText = `${activeData.enhancedPost || ''}\n\n${(activeData.hashtags || []).join(' ')}`;
        navigator.clipboard.writeText(fullText);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const handleGenerateHook = async () => {
        if (!activeData) return;
        try {
            const result = await generateHookMutation.mutateAsync({
                text: activeData.enhancedPost || '',
                tone: activeTab,
                hookTip: activeData.hookTip || ''
            });
            setGeneratedHooks(prev => ({
                ...prev,
                [activeTab]: result.hook
            }));
        } catch (error) {}
    };

    const downloadWord = async () => {
        if (!activeData) return;
        try {
            const title = activeData.title || 'Enhanced Content';
            const children = [
                new Paragraph({
                    text: title,
                    heading: HeadingLevel.HEADING_1,
                    alignment: AlignmentType.CENTER,
                    spacing: { after: 400 },
                }),
                new Paragraph({
                    children: [
                        new TextRun({ text: `Tone: ${activeTab}`, bold: true }),
                        new TextRun({ text: ` | Generated by GhostPost`, color: "666666" }),
                    ],
                    alignment: AlignmentType.CENTER,
                    spacing: { after: 400 },
                }),
            ];
            
            const postContent = activeData.enhancedPost || '';
            postContent.split('\n').forEach(line => {
                children.push(new Paragraph({ text: line.trim(), spacing: { after: 200 } }));
            });

            const doc = new Document({ sections: [{ children }] });
            const blob = await Packer.toBlob(doc);
            saveAs(blob, `${title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.docx`);
        } catch (error) {
            alert(`Failed to generate Word document.`);
        }
    };

    const downloadPDF = async () => {
        if (!activeData) return;
        try {
            const doc = new jsPDF();
            const title = activeData.title || 'Enhanced Content';
            doc.setFontSize(22);
            doc.text(title, 20, 30);
            doc.setFontSize(11);
            doc.text(activeData.enhancedPost || '', 20, 50, { maxWidth: 170 });
            doc.save(`${title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.pdf`);
        } catch (error) {
            alert('Failed to generate PDF.');
        }
    };

    return (
        <div className="flex flex-col h-full space-y-6">
            {/* Tone Selector Tabs - ALWAYS VISIBLE */}
            <div className="glass p-1.5 rounded-2xl flex gap-1 border border-white/10 z-20 relative">
                {tones.map((tone) => {
                    const Icon = tone.icon;
                    const hasDataForTone = !!data[tone.id];
                    return (
                        <button
                            key={tone.id}
                            onClick={() => setActiveTab(tone.id)}
                            className={`
                                flex-1 flex flex-col items-center gap-1.5 py-3 px-2 rounded-xl transition-all relative
                                ${activeTab === tone.id 
                                    ? 'bg-primary text-white shadow-lg' 
                                    : 'text-gray-500 hover:text-white hover:bg-white/5'}
                            `}
                        >
                            <Icon size={18} />
                            <span className="text-[10px] font-black uppercase tracking-tighter hidden sm:block">
                                {tone.label}
                            </span>
                            {hasDataForTone && (
                                <div className="absolute top-2 right-2 w-1.5 h-1.5 bg-green-400 rounded-full shadow-[0_0_8px_rgba(74,222,128,0.5)]" />
                            )}
                        </button>
                    );
                })}
            </div>

            {/* Content Area */}
            <div className="glass rounded-3xl overflow-hidden border border-white/10 flex flex-col min-h-[500px] transition-all duration-500 relative">
                {activeData ? (
                    <>
                        <div className="bg-white/5 p-4 flex justify-between items-center border-b border-white/10">
                            <div className="flex items-center gap-3">
                                {(() => {
                                    const ToneIcon = tones.find(t => t.id === activeTab)?.icon || Sparkles;
                                    return <ToneIcon size={16} className="text-primary" />;
                                })()}
                                <h4 className="text-heading font-bold text-gray-300 uppercase tracking-widest">{activeTab} Tone</h4>
                            </div>
                            <button
                                onClick={copyToClipboard}
                                className="flex items-center gap-2 text-body font-bold bg-white/10 hover:bg-white/20 px-4 py-2 rounded-xl transition-all border border-white/5"
                            >
                                {copied ? (
                                    <>
                                        <Check size={14} className="text-green-500" />
                                        Copied!
                                    </>
                                ) : (
                                    <>
                                        <Copy size={14} />
                                        Copy
                                    </>
                                )}
                            </button>
                        </div>
                        <div className="p-8 bg-black/20 max-h-[600px] overflow-y-auto text-gray-200 whitespace-pre-wrap leading-relaxed custom-scrollbar text-body font-medium">
                            {activeData.enhancedPost}
                            <div className="mt-12 pt-8 border-t border-white/5 flex flex-wrap gap-2">
                                {(activeData.hashtags || []).map((tag) => (
                                    <span key={tag} className="text-body text-primary font-bold hover:text-white transition-colors cursor-pointer bg-primary/5 px-3 py-1.5 rounded-lg border border-primary/10">
                                        {tag}
                                    </span>
                                ))}
                            </div>
                        </div>
                    </>
                ) : (
                    <div className="flex-1 flex flex-col items-center justify-center p-12 text-center group">
                        <div className="w-20 h-20 bg-white/5 rounded-3xl flex items-center justify-center mb-6 group-hover:scale-110 group-hover:bg-primary/10 transition-all duration-500">
                            {(() => {
                                const ToneIcon = tones.find(t => t.id === activeTab)?.icon || Sparkles;
                                return <ToneIcon size={32} className="text-gray-500 group-hover:text-primary transition-colors" />;
                            })()}
                        </div>
                        <h3 className="text-title font-black text-gray-200 mb-2 uppercase tracking-widest">
                            Ready for {activeTab} Tone?
                        </h3>
                        <p className="text-body text-gray-500 mb-8 max-w-[280px]">
                            Click generate below to have our agents craft a custom {activeTab.toLowerCase()} variant for you.
                        </p>
                        
                        <button
                            onClick={() => onGenerate(activeTab)}
                            disabled={isPending}
                            className="premium-gradient text-white px-8 py-4 rounded-2xl font-black uppercase tracking-widest flex flex-col items-center gap-1 shadow-xl hover:scale-105 transition-all disabled:opacity-50 disabled:grayscale disabled:scale-100 group/btn"
                        >
                            <div className="flex items-center gap-3">
                                {isPending ? (
                                    <Loader2 size={18} className="animate-spin" />
                                ) : (
                                    <Wand2 size={18} className="group-hover/btn:rotate-12 transition-transform" />
                                )}
                                <span>
                                    {isPending ? 'Agents Working...' : `Generate ${activeTab} Tone`}
                                </span>
                            </div>
                            {isPending && (
                                <span className="text-[9px] opacity-70 lowercase font-medium animate-pulse">
                                    Orchestrating {activeTab.toLowerCase()} variant...
                                </span>
                            )}
                        </button>
                    </div>
                )}
            </div>

            {hasData && (
                <>
                    <div className="grid grid-cols-2 gap-4">
                        <div className="glass p-5 rounded-3xl border border-white/5 flex flex-col items-center justify-center text-center group hover:bg-primary/5 transition-all">
                            <div className="text-[10px] text-gray-500 uppercase tracking-widest font-black mb-2">Hook Score</div>
                            <div className="text-title font-black text-primary flex items-baseline gap-1">
                                {activeData.hookScore || 0}
                                <span className="text-[10px] text-gray-600">/10</span>
                            </div>
                        </div>
                        <div className="glass p-5 rounded-3xl border border-white/5 flex flex-col items-center justify-center text-center group hover:bg-green-500/5 transition-all">
                            <div className="text-[10px] text-gray-500 uppercase tracking-widest font-black mb-2">Trust Score</div>
                            <div className="text-title font-black text-green-400 flex items-baseline gap-1">
                                {activeData.confidenceScore || 0}
                                <span className="text-[10px] text-gray-600">%</span>
                            </div>
                        </div>
                    </div>

                    {/* Hook Generator Section */}
                    <div className="glass p-6 rounded-3xl border border-white/5">
                        <div className="flex items-start gap-4">
                            <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center text-primary">
                                <Info size={20} />
                            </div>
                            <div className="flex-1 pt-1">
                                <p className="text-[10px] text-gray-500 uppercase tracking-widest font-black mb-2">Optimization Strategy</p>
                                <p className="text-body text-gray-200 font-medium leading-relaxed mb-6 italic">"{activeData.hookTip}"</p>
                                
                                {!generatedHooks[activeTab] ? (
                                    <button
                                        onClick={handleGenerateHook}
                                        disabled={generateHookMutation.isPending}
                                        className="bg-white/5 hover:bg-white/10 border border-white/10 text-[12px] font-black text-white px-6 py-3 rounded-xl flex items-center gap-3 transition-all disabled:opacity-50"
                                    >
                                        {generateHookMutation.isPending ? <Loader2 size={16} className="animate-spin" /> : <Wand2 size={16} />}
                                        Generate Custom Hook
                                    </button>
                                ) : (
                                    <div className="p-5 bg-primary/5 border border-primary/20 rounded-2xl relative group border-l-4 border-l-primary shadow-2xl">
                                        <p className="text-lg text-white leading-relaxed font-bold italic">
                                            "{generatedHooks[activeTab]}"
                                        </p>
                                    </div>
                                )}
                            </div>
                        </div>
                    </div>

                    {/* Export Options */}
                    <div className="flex flex-col sm:flex-row gap-4">
                        <button
                            onClick={downloadPDF}
                            className="flex-1 bg-white/5 hover:bg-white/10 border border-white/10 text-white font-bold py-4 rounded-2xl flex items-center justify-center gap-3 transition-all"
                        >
                            <Download size={18} className="text-primary" />
                            Download PDF
                        </button>
                        <button
                            onClick={downloadWord}
                            className="flex-1 premium-gradient hover:opacity-90 text-white font-black py-4 rounded-2xl flex items-center justify-center gap-3 transition-all shadow-xl shadow-primary/40"
                        >
                            <Download size={18} />
                            Download Word
                        </button>
                    </div>
                </>
            )}
        </div>
    );
}
