import { useState } from 'react';
import { Copy, Check, Loader2, Download, ChevronDown, Sparkles } from 'lucide-react';
import type { EnhanceResponse } from '../hooks/useEnhance';
import jsPDF from 'jspdf';
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from 'docx';
import { saveAs } from 'file-saver';

interface OutputDisplayProps {
    data: Partial<EnhanceResponse>;
    activeTone: 'professional' | 'conversational' | 'story' | 'bold';
    isPending?: boolean;
}

const toneMapping: Record<string, keyof EnhanceResponse> = {
    professional: 'Professional',
    conversational: 'Conversational',
    story: 'Storytelling',
    bold: 'Bold/Contrarian'
};

export default function OutputDisplay({ data, activeTone, isPending }: OutputDisplayProps) {
    const [copied, setCopied] = useState(false);
    const [showDownloadMenu, setShowDownloadMenu] = useState(false);

    const mappedKey = toneMapping[activeTone];
    const activeData = data[mappedKey] || (data as any)[activeTone];

    const copyToClipboard = () => {
        if (!activeData) return;
        const hookText = activeData.hook ? `HOOK: ${activeData.hook}\n\n` : '';
        const fullText = `${hookText}${activeData.enhancedPost || ''}\n\n${(activeData.hashtags || []).join(' ')}`;
        navigator.clipboard.writeText(fullText);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const sanitizeFilename = (title: string, extension: string) => {
        const cleanTitle = title.replace(/[^a-z0-9]/gi, '_').replace(/_{2,}/g, '_').toLowerCase();
        const finalTitle = cleanTitle.length > 0 ? cleanTitle : 'ghostpost_export';
        const timestamp = new Date().toISOString().split('T')[0];
        return `${finalTitle}_${timestamp}.${extension}`;
    };

    const downloadWord = async () => {
        if (!activeData) return;
        try {
            const title = activeData.title || 'Enhanced Content';
            const children = [
                new Paragraph({
                    text: title.toUpperCase(),
                    heading: HeadingLevel.HEADING_1,
                    alignment: AlignmentType.CENTER,
                    spacing: { after: 400 },
                }),
                new Paragraph({
                    children: [
                        new TextRun({ text: `Tone: ${mappedKey}`, bold: true }),
                        new TextRun({ text: ` | Generated by GhostPost`, color: "666666" }),
                        new TextRun({ text: ` | ${new Date().toLocaleDateString()}`, color: "999999" }),
                    ],
                    alignment: AlignmentType.CENTER,
                    spacing: { after: 600 },
                }),
            ];
            
            const postContent = activeData.enhancedPost || '';
            const hook = activeData.hook || '';

            if (hook) {
                children.push(new Paragraph({
                    children: [
                        new TextRun({ text: "HOOK:", bold: true, size: 20 }),
                        new TextRun({ text: ` ${hook}`, size: 20 }),
                    ],
                    spacing: { after: 400 },
                }));
            }

            postContent.split('\n').forEach((line: string) => {
                const trimmed = line.trim();
                if (trimmed) {
                    children.push(new Paragraph({ 
                        text: trimmed, 
                        spacing: { after: 200 },
                        alignment: AlignmentType.LEFT
                    }));
                } else {
                    children.push(new Paragraph({ spacing: { after: 100 } }));
                }
            });

            const doc = new Document({ 
                title,
                creator: "GhostPost",
                sections: [{ children }] 
            });
            const blob = await Packer.toBlob(doc);
            saveAs(blob, sanitizeFilename(title, 'docx'));
            setShowDownloadMenu(false);
        } catch (error) {
            // Silently handled
        }
    };

    const downloadPDF = async () => {
        if (!activeData) return;
        try {
            const doc = new jsPDF();
            const title = activeData.title || 'Enhanced Content';
            const content = activeData.enhancedPost || '';
            const hook = activeData.hook || '';
            
            // Header
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(20);
            doc.text(title.toUpperCase(), 105, 25, { align: 'center' });
            
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(10);
            doc.setTextColor(100);
            doc.text(`Tone: ${mappedKey} | Generated by GhostPost`, 105, 33, { align: 'center' });
            
            doc.setDrawColor(200);
            doc.line(20, 38, 190, 38);

            let cursorY = 48;
            const pageHeight = doc.internal.pageSize.height;
            const marginBottom = 25;

            // Hook Section
            if (hook) {
                doc.setFont('helvetica', 'bold');
                doc.setFontSize(11);
                doc.setTextColor(0);
                doc.text("HOOK:", 20, cursorY);
                cursorY += 7;
                
                doc.setFont('helvetica', 'italic');
                doc.setTextColor(60);
                const splitHook = doc.splitTextToSize(hook, 170);
                
                splitHook.forEach((line: string) => {
                    if (cursorY > pageHeight - marginBottom) {
                        doc.addPage();
                        cursorY = 20;
                    }
                    doc.text(line, 20, cursorY);
                    cursorY += 6;
                });
                cursorY += 6;
            }

            // Body Content
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(11);
            doc.setTextColor(0);
            
            const splitText = doc.splitTextToSize(content, 170);
            splitText.forEach((line: string) => {
                if (cursorY > pageHeight - marginBottom) {
                    doc.addPage();
                    cursorY = 20;
                }
                doc.text(line, 20, cursorY);
                cursorY += 7;
            });

            // Footer
            const totalPages = doc.getNumberOfPages();
            for (let i = 1; i <= totalPages; i++) {
                doc.setPage(i);
                doc.setFontSize(8);
                doc.setTextColor(150);
                doc.text(`Page ${i} of ${totalPages} | GhostPost Content OS`, 105, pageHeight - 12, { align: 'center' });
            }

            doc.save(sanitizeFilename(title, 'pdf'));
            setShowDownloadMenu(false);
        } catch (error) {
            // Silently handled
        }
    };

    const downloadMarkdown = () => {
        if (!activeData) return;
        try {
            const title = activeData.title || 'Enhanced Content';
            const hook = activeData.hook ? `## HOOK\n${activeData.hook}\n\n` : '';
            const hashtags = (activeData.hashtags || []).length > 0 
                ? `\n\n${activeData.hashtags.join(' ')}` 
                : '';
            
            const content = `# ${title.toUpperCase()}\n\n${hook}${activeData.enhancedPost || ''}${hashtags}\n\n---\n*Generated by GhostPost Content OS*`;
            
            const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
            saveAs(blob, sanitizeFilename(title, 'md'));
            setShowDownloadMenu(false);
        } catch (error) {
            // Silently handled
        }
    };


    return (
        <div className="flex gap-3 w-full animate-in fade-in slide-in-from-bottom-2 duration-300">
            {/* AI Avatar */}
            <div className="w-7 h-7 rounded-full bg-[var(--violet-dim)] border border-[var(--violet)]/30 flex items-center justify-center shrink-0 mt-1">
                <Sparkles size={14} className="text-[var(--violet)]" />
            </div>

            {/* Content Card */}
            <div className="flex-1 min-w-0 bg-[var(--void-surface)] border border-[var(--border)] rounded-[6px] overflow-hidden">
                {isPending ? (
                    <div className="p-8 flex flex-col items-center justify-center text-[var(--text-3)] gap-4">
                        <Loader2 size={24} className="animate-spin text-[var(--plasma)]" />
                        <p className="animate-pulse font-geist text-[11px] uppercase tracking-widest">Orchestrating Variants...</p>
                    </div>
                ) : activeData ? (
                    <div className="p-4">
                        {/* Meta Row */}
                        <div className="flex items-center justify-between mb-4">
                            <div className="flex items-center gap-3">
                                <span className="text-[10px] font-geist font-bold bg-[var(--violet-dim)] text-[var(--violet)] px-2 py-0.5 rounded-[2px] uppercase tracking-wider">
                                    {mappedKey}
                                </span>
                                <div className="flex items-center gap-3 border-l border-[var(--border)] pl-3">
                                    <div className="flex items-center gap-1.5">
                                        <span className="text-[var(--text-3)] text-[10px] font-geist">HOOK:</span>
                                        <span className="text-[var(--plasma)] font-geist font-bold text-[11px]">{activeData.hookScore || 0}/10</span>
                                    </div>
                                    <div className="flex items-center gap-1.5">
                                        <span className="text-[var(--text-3)] text-[10px] font-geist">CONF:</span>
                                        <span className="text-[var(--success)] font-geist font-bold text-[11px]">{activeData.confidenceScore || 0}%</span>
                                    </div>
                                </div>
                            </div>

                            <div className="flex items-center gap-3">
                                <button
                                    onClick={copyToClipboard}
                                    className="text-[var(--text-2)] hover:text-[var(--text-1)] transition-colors flex items-center gap-1 text-[11px] font-medium"
                                >
                                    {copied ? <Check size={12} className="text-[var(--success)]" /> : <Copy size={12} />}
                                    {copied ? 'Copied' : 'Copy'}
                                </button>
                                
                                <div className="relative">
                                    <button
                                        onClick={() => setShowDownloadMenu(!showDownloadMenu)}
                                        className="text-[var(--text-2)] hover:text-[var(--text-1)] transition-all flex items-center gap-1 text-[11px] font-medium"
                                    >
                                        <Download size={12} />
                                        <span>Export</span>
                                        <ChevronDown size={10} className={`transition-transform ${showDownloadMenu ? 'rotate-180' : ''}`} />
                                    </button>

                                    {showDownloadMenu && (
                                        <div className="absolute right-0 mt-2 w-28 bg-[var(--void-surface-2)] border border-[var(--border)] rounded-[4px] shadow-2xl z-50 flex flex-col overflow-hidden">
                                            <button onClick={downloadPDF} className="w-full text-left px-3 py-2 hover:bg-[var(--plasma-dim)] text-[var(--text-2)] hover:text-[var(--text-1)] text-[11px] font-medium transition-colors">
                                                PDF Document
                                            </button>
                                            <button onClick={downloadWord} className="w-full text-left px-3 py-2 hover:bg-[var(--plasma-dim)] text-[var(--text-2)] hover:text-[var(--text-1)] text-[11px] font-medium transition-colors">
                                                Word Doc
                                            </button>
                                            <button onClick={downloadMarkdown} className="w-full text-left px-3 py-2 hover:bg-[var(--plasma-dim)] text-[var(--text-2)] hover:text-[var(--text-1)] text-[11px] font-medium transition-colors">
                                                Markdown (.md)
                                            </button>
                                        </div>
                                    )}
                                </div>
                            </div>
                        </div>

                        {/* Hook - Moved to Top */}
                        {activeData.hook && (
                            <div className="mb-5 pl-4 border-l-2 border-[var(--plasma)] text-[var(--text-1)] text-[13px] bg-[var(--plasma-glow)] py-3 pr-2 rounded-r-[4px]">
                                <span className="font-bold text-[10px] uppercase text-[var(--plasma)] block mb-1 tracking-wider">Hook</span>
                                {activeData.hook}
                            </div>
                        )}

                        {/* Hook Strategy (Internal Tip) */}
                        {activeData.hookTip && (
                             <div className="mb-4 flex items-center gap-2 text-[10px] text-[var(--text-3)] font-geist italic px-1">
                                <Sparkles size={10} className="text-[var(--plasma)]/50" />
                                <span>Strategy: {activeData.hookTip}</span>
                             </div>
                        )}

                        {/* Main Content */}
                        <div className="text-[13px] text-[var(--text-1)] whitespace-pre-wrap leading-relaxed">
                            {activeData.enhancedPost}
                        </div>

                        {/* Hashtags */}
                        {activeData.hashtags && activeData.hashtags.length > 0 && (
                            <div className="flex flex-wrap gap-2 mt-5">
                                {activeData.hashtags.map((tag: string) => (
                                    <span key={tag} className="text-[var(--plasma)]/60 text-[11px] font-geist">
                                        #{tag.replace('#', '')}
                                    </span>
                                ))}
                            </div>
                        )}
                    </div>
                ) : null}
            </div>
        </div>
    );
}
