import axios from 'axios';
import { BaseAgent, AgentResponse } from './base.agent';
import config, { PromptOptions } from '../../config';
import { extractJsonString, extractAndParseJson } from '../../utils/json.util';

export class DraftingAgent extends BaseAgent {
    constructor(requestId?: string) {
        super('DraftingAgent', requestId);
    }

    /**
     * Gathers real-time research and statistics on a topic.
     * Resilience Pattern: Wrapped in withRetry to handle unstable web-research APIs.
     */
    public async research(topic: string): Promise<AgentResponse> {
        this.log('Performing web research...', { topic });

        if (config.drafting.isMockMode) {
            return {
                success: true,
                data: this.getMockResearch(topic),
                metadata: { source: 'mock' }
            };
        }

        return this.withRetry(async () => {
            const baseUrl = config.research.url;
            const response = await axios.post(baseUrl, {
                model: config.research.model,
                messages: [
                    {
                        role: 'system',
                        content: 'You are a research assistant. Provide specific, high-value information, including direct quotes, obscure statistics, and tactical "insider" details. Avoid generic summaries; focus on the "messy" details that give an article authenticity. ALWAYS include the source URLs for every fact in markdown link format [Source Name](URL).'
                    },
                    {
                        role: 'user',
                        content: `Research the following topic and provide key facts and statistics with their source URLs: ${topic}`
                    }
                ],
                max_tokens: 1000,
            }, {
                headers: {
                    'Authorization': `Bearer ${config.research.apiKey}`,
                    'Content-Type': 'application/json',
                }
            });

            const content = response.data.choices[0].message.content;
            if (!content) throw new Error('No content returned from Research Agent');

            return { success: true, data: content, metadata: { model: config.drafting.model } };
        });
    }

    /**
     * Generates an initial draft (Article or Post) based on input and research.
     * Resilience Pattern: Wrapped in withRetry to ensure drafting succeeds even if first request times out.
     */
    public async draft(options: PromptOptions & { mode: 'article' | 'post' }): Promise<AgentResponse> {
        this.log('Generating draft...', { mode: options.mode, tone: options.tone });

        const prompt = options.mode === 'article'
            ? config.prompts.article(options)
            : config.prompts.post(options);

        if (config.drafting.isMockMode) {
            return {
                success: true,
                data: JSON.stringify({
                    title: `Mock ${options.tone} Title`,
                    hook: `This is a generated mock hook for the ${options.tone} tone.`,
                    enhancedPost: `(MOCK) Draft for ${options.tone} tone. This content has been generated by the DraftingAgent in mock mode.`,
                    hookScore: 7,
                    hookTip: "Try a more controversial opening.",
                    hashtags: ["#mock", "#drafting"]
                })
            };
        }

        return this.withRetry(async () => {
            const baseUrl = config.helicone.enabled ? config.helicone.baseUrl : config.drafting.url;
            const requestBody = {
                model: config.drafting.model,
                messages: [
                    {
                        role: 'system',
                        content: 'You are an elite copywriter and ghostwriter.'
                    },
                    {
                        role: 'user',
                        content: prompt
                    }
                ],
                max_tokens: options.mode === 'article' ? 4000 : 1000,
            };

            const response = await axios.post(baseUrl, requestBody, {
                headers: {
                    'Authorization': `Bearer ${config.drafting.apiKey}`,
                    'Content-Type': 'application/json',
                    ...this.getHeliconeHeaders(`drafting-${options.mode}`)
                }
            });

            let content = response.data.choices[0].message.content;
            if (!content) throw new Error('No content returned from Drafting Agent');

            return { success: true, data: content };
        });
    }

    private getMockResearch(topic: string): string {
        return `
            Mock Research Data for: "${topic}"
            - Stat 1: 75% of professionals believe ${topic} will impact their industry by 2030.
            - Fact 2: Industry leaders have seen a 20% increase in productivity when using ${topic} frameworks.
            - Trend 3: Global investment in ${topic}-related technologies reached $50B last year.
        `;
    }
}
